# TCL File Generated by Component Editor 13.0
# Thu Oct 03 17:35:59 CDT 2013
# DO NOT MODIFY


# 
# axi_conduit "AXI Conduit" v1.0
#  2013.10.03.17:35:59
# 
# 

# 
# request TCL package from ACDS 13.0
# 
package require -exact qsys 13.0


# 
# module axi_conduit
# 
set_module_property DESCRIPTION ""
set_module_property NAME axi_conduit
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Custom
set_module_property AUTHOR "Charles Steinkuehler"
set_module_property DISPLAY_NAME "AXI Conduit"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL axi_conduit
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file axi_conduit.vhd VHDL PATH axi_conduit.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point axi_in
# 
add_interface axi_in axi4 end
set_interface_property axi_in associatedClock clock
set_interface_property axi_in associatedReset reset
set_interface_property axi_in readAcceptanceCapability 16
set_interface_property axi_in writeAcceptanceCapability 16
set_interface_property axi_in combinedAcceptanceCapability 16
set_interface_property axi_in readDataReorderingDepth 1
set_interface_property axi_in ENABLED true
set_interface_property axi_in EXPORT_OF ""
set_interface_property axi_in PORT_NAME_MAP ""
set_interface_property axi_in SVD_ADDRESS_GROUP ""

add_interface_port axi_in axs_s0_awid awid Input 14
add_interface_port axi_in axs_s0_awaddr awaddr Input 14
add_interface_port axi_in axs_s0_awlen awlen Input 8
add_interface_port axi_in axs_s0_awsize awsize Input 3
add_interface_port axi_in axs_s0_awburst awburst Input 2
add_interface_port axi_in axs_s0_awvalid awvalid Input 1
add_interface_port axi_in axs_s0_awready awready Output 1
add_interface_port axi_in axs_s0_wdata wdata Input 32
add_interface_port axi_in axs_s0_wstrb wstrb Input 4
add_interface_port axi_in axs_s0_wvalid wvalid Input 1
add_interface_port axi_in axs_s0_wready wready Output 1
add_interface_port axi_in axs_s0_bid bid Output 14
add_interface_port axi_in axs_s0_bvalid bvalid Output 1
add_interface_port axi_in axs_s0_bready bready Input 1
add_interface_port axi_in axs_s0_arid arid Input 14
add_interface_port axi_in axs_s0_araddr araddr Input 14
add_interface_port axi_in axs_s0_arlen arlen Input 8
add_interface_port axi_in axs_s0_arsize arsize Input 3
add_interface_port axi_in axs_s0_arburst arburst Input 2
add_interface_port axi_in axs_s0_arvalid arvalid Input 1
add_interface_port axi_in axs_s0_arready arready Output 1
add_interface_port axi_in axs_s0_rdata rdata Output 32
add_interface_port axi_in axs_s0_rlast rlast Output 1
add_interface_port axi_in axs_s0_rvalid rvalid Output 1
add_interface_port axi_in axs_s0_rready rready Input 1
add_interface_port axi_in axs_s0_rid rid Output 14


# 
# connection point axi_out
# 
add_interface axi_out conduit end
set_interface_property axi_out associatedClock clock
set_interface_property axi_out associatedReset reset
set_interface_property axi_out ENABLED true
set_interface_property axi_out EXPORT_OF ""
set_interface_property axi_out PORT_NAME_MAP ""
set_interface_property axi_out SVD_ADDRESS_GROUP ""

add_interface_port axi_out axs_s1_awid export Output 14
add_interface_port axi_out axs_s1_awaddr export Output 14
add_interface_port axi_out axs_s1_awlen export Output 8
add_interface_port axi_out axs_s1_awsize export Output 3
add_interface_port axi_out axs_s1_awburst export Output 2
add_interface_port axi_out axs_s1_awvalid export Output 1
add_interface_port axi_out axs_s1_awready export Input 1
add_interface_port axi_out axs_s1_wdata export Output 32
add_interface_port axi_out axs_s1_wstrb export Output 4
add_interface_port axi_out axs_s1_wvalid export Output 1
add_interface_port axi_out axs_s1_wready export Input 1
add_interface_port axi_out axs_s1_bid export Input 14
add_interface_port axi_out axs_s1_bvalid export Input 1
add_interface_port axi_out axs_s1_bready export Output 1
add_interface_port axi_out axs_s1_arid export Output 14
add_interface_port axi_out axs_s1_araddr export Output 14
add_interface_port axi_out axs_s1_arlen export Output 8
add_interface_port axi_out axs_s1_arsize export Output 3
add_interface_port axi_out axs_s1_arburst export Output 2
add_interface_port axi_out axs_s1_arvalid export Output 1
add_interface_port axi_out axs_s1_arready export Input 1
add_interface_port axi_out axs_s1_rid export Input 14
add_interface_port axi_out axs_s1_rdata export Input 32
add_interface_port axi_out axs_s1_rlast export Input 1
add_interface_port axi_out axs_s1_rvalid export Input 1
add_interface_port axi_out axs_s1_rready export Output 1
add_interface_port axi_out clk_o export Output 1
add_interface_port axi_out reset_o export Output 1

